# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Swedish Biodiversity Data Infrastructure
tagline: Open access to Sweden's biodiversity data
description: >-
  The Swedish Biodiversity Data Infrastructure (SBDI) is a national initiative
  to make biodiversity data available and accessible for research, education,
  and conservation.
logo: /assets/images/SBDI-rgb.svg
email: support@biodiversitydata.se
baseurl: ""
url: "https://biodiversitydata.se"
safe: false

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache/
  - node_modules/
  - script
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - docker-compose.yml
  - Dockerfile
  - dev.Dockerfile
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
