- title: Online courses
  items:
    - title: Access to biodiversity data through web services
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/access-to-biodiversity-data-through-web-services/
    - title: Basic spatial analysis in R
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/basic-spatial-analysis-in-r/
    - title: Advanced spatial analysis in R
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/advanced-spatial-analysis-in-r/
    - title: Basic Python for Biologists
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/basic-python-for-biologists/
    - title: Advanced Python for Biologists
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/advanced-python-for-biologists/
    - title: Basic phylogeography
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/basic-phylogeography/
    - title: Advanced phylogenetic analysis with SuperSmartR
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/supersmartr/
    - title: Biodiversity data mobilization course
      link: https://docs.biodiversitydata.se/courses-and-training/online-courses/biodiversity-data-mobilization-course/

- title: PhD, MSc, and BSc courses
  items:
    - title: Spatial Analysis in R - An introduction to accessing spatial biodiversity data and spatial analysis in R
      link: https://docs.biodiversitydata.se/courses-and-training/phd-courses/spatial-analysis-in-r-an-introduction-to-accessing-spatial-biodiversity-data-and-spatial-analysis-in-r/
    - title: Curation and Biodiversity Informatics
      link: Curation and Biodiversity Informatics 
    - title: Planning and analysis with the Heureka system - a forest decision support system 
      link: https://docs.biodiversitydata.se/courses-and-training/phd-courses/planning-and-analysis-with-the-heureka-system-a-forest-decision-support-system-sg0273/
    - title: Introduction to Python for data science
      link: https://docs.biodiversitydata.se/courses-and-training/phd-courses/introduction-to-python-for-data-science/
